server:
  port: ${PUBLICATION_SERVICE_SERVER_PORT:10000}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${PUBLICATION_SERVICE_ISSUER_URI:http://localhost:9000}

redis:
  client:
    host-name: ${PUBLICATION_SERVICE_HOST_NAME:localhost}
    port: ${PUBLICATION_SERVICE_PORT:6379}

logging:
  level:
    root: INFO
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.security.oauth2]': DEBUG
